app = "microcrm-client1"
primary_region = "mia"

[build]
  dockerfile = "Dockerfile"

[env]
  SITE_NAME = "microcrm-client1"
  PORT = "8000"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true

