# fly.toml app configuration file generated for microcrm-client1 on 2025-06-05T10:17:38-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'microcrm-client1'
primary_region = 'mia'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[env]
  INSTALL_APPS = 'frappe_crm'
  MYSQL_ROOT_PASSWORD = 'root'
  SITE_NAME = 'microcrm.local'
  PORT = "8080"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true